// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/calculate-coast-fire.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var calculate_coast_fire_default = defineTool({
  name: "calculate_coast_fire",
  title: "Calculate Coast FIRE number",
  description: "Calculate the Coast FIRE number: the invested amount today that, left to grow untouched, funds retirement at the target age. Returns coast number, projected value at retirement, and annual withdrawal at the safe withdrawal rate.",
  inputSchema: {
    currentAge: z.number().int().min(0).max(100).describe("Current age of the user."),
    retirementAge: z.number().int().min(1).max(100).describe("Age at which the user plans to retire."),
    annualExpenses: z.number().positive().describe("Expected annual expenses in retirement (today's dollars)."),
    realReturnRate: z.number().describe("Expected annual real (inflation-adjusted) return, e.g. 0.05 for 5%. Defaults to 0.05.").default(0.05),
    withdrawalRate: z.number().describe("Safe withdrawal rate, e.g. 0.04 for the 4% rule. Defaults to 0.04.").default(0.04)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ currentAge, retirementAge, annualExpenses, realReturnRate, withdrawalRate }) => {
    if (retirementAge <= currentAge) {
      return {
        content: [{ type: "text", text: "retirementAge must be greater than currentAge." }],
        isError: true
      };
    }
    const fireNumber = annualExpenses / withdrawalRate;
    const years = retirementAge - currentAge;
    const coastNumber = fireNumber / Math.pow(1 + realReturnRate, years);
    const summary = `FIRE number: $${fireNumber.toLocaleString(void 0, { maximumFractionDigits: 0 })}
Coast FIRE number (invest today, coast to retirement): $${coastNumber.toLocaleString(void 0, { maximumFractionDigits: 0 })}
Years of growth: ${years}
Assumptions: ${(realReturnRate * 100).toFixed(1)}% real return, ${(withdrawalRate * 100).toFixed(1)}% SWR.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        fireNumber,
        coastNumber,
        yearsToRetirement: years,
        realReturnRate,
        withdrawalRate
      }
    };
  }
});

// src/lib/mcp/tools/compound-growth.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var compound_growth_default = defineTool2({
  name: "compound_growth",
  title: "Project compound investment growth",
  description: "Project the future value of an investment given a starting balance, monthly contributions, annual return rate, and number of years.",
  inputSchema: {
    startingBalance: z2.number().min(0).describe("Current invested balance."),
    monthlyContribution: z2.number().min(0).describe("Amount contributed each month."),
    annualReturnRate: z2.number().describe("Expected annual return, e.g. 0.07 for 7%."),
    years: z2.number().positive().describe("Number of years to project.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ startingBalance, monthlyContribution, annualReturnRate, years }) => {
    const months = Math.round(years * 12);
    const monthlyRate = annualReturnRate / 12;
    let balance = startingBalance;
    for (let i = 0; i < months; i++) {
      balance = balance * (1 + monthlyRate) + monthlyContribution;
    }
    const totalContributed = startingBalance + monthlyContribution * months;
    const growth = balance - totalContributed;
    return {
      content: [
        {
          type: "text",
          text: `Future value after ${years} years: $${balance.toLocaleString(void 0, { maximumFractionDigits: 0 })}
Total contributed: $${totalContributed.toLocaleString(void 0, { maximumFractionDigits: 0 })}
Investment growth: $${growth.toLocaleString(void 0, { maximumFractionDigits: 0 })}`
        }
      ],
      structuredContent: { futureValue: balance, totalContributed, growth, months }
    };
  }
});

// src/lib/mcp/tools/list-calculators.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CALCULATORS = [
  { name: "Coast FIRE Tracker", path: "/coast-fire-tracker", description: "Track progress toward Coast FIRE with milestone chart." },
  { name: "Coast FIRE Calculator", path: "/coast-fire-calculator", description: "Calculate your Coast FIRE number by age." },
  { name: "Early Retirement Calculator", path: "/early-retirement-calculator", description: "Project when you can retire early." },
  { name: "Financial Independence Calculator", path: "/financial-independence-calculator", description: "Determine your FI number and timeline." },
  { name: "Monthly Dividend Calculator", path: "/monthly-dividend-calculator", description: "Estimate monthly dividend income needs." },
  { name: "Covered Call Calculator", path: "/covered-call-calculator", description: "Model covered call option income." },
  { name: "Paycheck Calculator", path: "/paycheck-calculator", description: "Break down paycheck taxes and deductions." },
  { name: "Dividend Tracker", path: "/dividend-tracker", description: "Track dividend portfolio, YOC, and CAGR." }
];
var list_calculators_default = defineTool3({
  name: "list_calculators",
  title: "List Profit Pathfinder calculators",
  description: "List the financial calculators and tools available on Profit Pathfinder, with their URLs and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: CALCULATORS.map((c) => `\u2022 ${c.name} \u2014 ${c.description} (https://profitpathfinder.online${c.path})`).join("\n")
      }
    ],
    structuredContent: { calculators: CALCULATORS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "profit-pathfinder-mcp",
  title: "Profit Pathfinder MCP",
  version: "0.1.0",
  instructions: "Tools for Profit Pathfinder, a personal-finance and FIRE planning app. Use `list_calculators` to discover available in-app tools, `calculate_coast_fire` to compute a Coast FIRE number, and `compound_growth` to project long-term investment growth.",
  tools: [calculate_coast_fire_default, compound_growth_default, list_calculators_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
